# Generated by Django 3.0.7 on 2021-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_auto_20210224_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprofile',
            name='best_image',
            field=models.ImageField(default='noimage2.jpg', upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='image',
            field=models.ImageField(default='noimage2.jpg', upload_to='vehicles'),
        ),
    ]
