# Generated by Django 3.0.7 on 2021-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_auto_20210302_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprofile',
            name='best_image',
            field=models.ImageField(default='noimage2.png', upload_to='vehicles'),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='image',
            field=models.ImageField(default='noimage2.png', upload_to='vehicles'),
        ),
    ]
