# Generated by Django 3.0.7 on 2021-03-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_auto_20210303_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(max_length=30),
        ),
    ]
